

mingw:
	g++ -g -O3 -D_NANO_MINGW_ -o Engine_3D.exe Engine_3D.cpp reader/3DS.cpp reader/OBJ.cpp flatform/Drawable.cpp flatform/EPaint.cpp math3d/Texture.cpp common/EPoint.cpp common/MultiLinkLocal.cpp  -lgraphics -lgdiplus -limm32 -lmsimg32 -lole32 -loleaut32 -lwinmm -luuid -mwindows -mconsole
	
run:
	./Engine_3D.exe
